### ISSUE TITLE
Customize resolution

### ISSUE THREAD

**Issue by Bercof** [LabEG/centos-lxqt-vnc#1]
As a user I want to set screen resolution as a parameter for container.
This could be easily implemented in startup.sh:

```
# set screen resolution from environment variable 'resolution' or default 1820x960
set SCREEN_RESOLUTION 1820x960
catch {set SCREEN_RESOLUTION $env(resolution)}

spawn /usr/bin/vncserver :1 -fg -geometry $SCREEN_RESOLUTION
```

And container may be run with an option `-e resolution='1920x1080'`

**Comment by LabEG** [comment]
Thank you for your help! Updated. Tested. Published in Dockerhub!

**Comment by Bercof** [comment]
Thank you.
