### ISSUE TITLE
The same in Ubuntu?

### ISSUE THREAD

**Issue by win32nipuh** [LabEG/centos-lxqt-vnc#2]
Хочу построить докер типа такого же, но с Убунту.
Вы не планируете сделать такой эксперимент?

**Comment by LabEG** [comment]
Нет. Мне ближе производные от red hat =)
С Убунту логика действий аналогичная, надо только поменять yum на apt-get, и название пакета lxqt в убунту другой.

**Comment by win32nipuh** [comment]
Я сделал внешний фолдер на хосте для Pictures в CentOS, монтируется на старте докера, чисто для эксперимента, извечная тяга к знаниям :-)

**Comment by LabEG** [comment]
Я сделал так же для statefull контейнеров. Каждую ночь собирается новый чистый контейнер, watchtower видит новую сборку и деплоит ее, и на утро у меня свежий софт без вчерашнего мусора, но с сохраненными наработками.

**Comment by ZedZipDev** [comment]
Понимаю, что оффтопик здесь, но может, быть вы в курсе
Я, пытался понять, как сделать так:
докер (linux+postgresql или mysql) с какой-то минимальной базой, отдаю тестировать или как демо юзеру.
Как сделать так, чтобы после рестарта докера база сохраняла данные, а не сбрасывала в первоначальное состояние каждый раз?

**Comment by LabEG** [comment]
Нужно использовать volume для сохранения состояния базы.
Пример можно найти в контейнере postgres
https://hub.docker.com/_/postgres
